#!/bin/sh

# Simple script that locks the screen, displaying a pixelized screenshot

scrot -q 1 /tmp/lock_screenshot.png
convert /tmp/lock_screenshot.png -scale 96x54! -scale 1920x1080! \
	/tmp/lock_screenshot.png
magick composite -gravity center ~/Documents/repositories/dotfiles/enter_password.png \
	/tmp/lock_screenshot.png /tmp/lock_screenshot.png
feh -x -F -Y /tmp/lock_screenshot.png &
screen_processID=$!
slock
kill $screen_processID
