# TODO: make all often used normal keys homerow +/- 1
# Remap movement keys (plus modifiers)
map global normal n j
map global normal N J
map global normal e k
map global normal E K
map global normal i l
map global normal I L
map global normal o h
map global normal O H
map global normal <a-o> <a-h>
map global normal <a-i> <a-l>

# Remap scrolling
map global normal <c-e> <c-u>
map global normal <c-n> <c-d>

# Other remaps
map global normal l i
map global normal L I
map global normal k o
map global normal K O
map global normal h e
map global normal H E
map global normal j n
map global normal J N

# TODO map scrolling
# Line numbering
addhl global/ number-lines
# Line wrapping
addhl global/ wrap
# TODO color column 72
#
# Black autoformatting
hook global WinSetOption filetype=python %{
    set-option window formatcmd 'black -q  -'
    hook buffer BufWritePre .* %{format}
}
