#!/bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 lock

bspc config border_width         4
bspc config window_gap         	 6 

# Color configuration
# %%base16_template: bspwm##default %%
# base16-gruvbox-dark-hard

bspc config active_border_color \#d5c4a1
bspc config normal_border_color \#1d2021
# %%base16_template_end%%

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

sxhkd &
dunst &