#!/bin/bash

# Send battery and time notification
capacity=$(cat /sys/class/power_supply/BAT0/capacity)
status=$(cat /sys/class/power_supply/BAT0/status)
current_time=$(date +%H:%M)

if [ $status = "Charging" ]
then
	notify-send "$capacity% ▲ $current_time"
else
	notify-send "$capacity% ▼ $current_time"
fi
