#!/bin/bash

# A simple shutdown prompt with a custom image

# TODO: Fix autoselect in sway
# TODO: Change feh to sway compatible image viewer

# Display image with following options
# (p)oweroff
# (h)ibernate
# (s)uspend
# (r)eboot
feh -F -Y ~/repositories/dotfiles/misc/shutdown_prompt.png &

# Read a single character
choice=$(echo -e "p\nh\ns\nr" | wofi --dmenu)

# Execute the chosen option
if [ $choice = 'p' ]
then
	systemctl poweroff
fi
if [ $choice = 'h' ]
then
	systemctl hibernate
fi
if [ $choice = 's' ]
then
	systemctl suspend
fi
if [ $choice = 'r' ]
then
	systemctl reboot
fi
