#!/bin/bash

# A simple shutdown prompt with a custom image

# Display image with following options
# (p)oweroff
# (h)ibernate
# (s)uspend
# (r)eboot
imv -c "bind p exec systemctl poweroff;quit" \
    -c "bind h exec systemctl hibernate;quit" \
    -c "bind s exec systemctl suspend;quit" \
    -c "bind r exec systemctl reboot;quit" \
    -f ~/repositories/dotfiles/misc/shutdown_prompt.png
