#!/bin/sh

# Script to automatically and realtime sync local changes to netcache

destination="/mnt/netcache/pelvis/projects/bram/repos"
paths="/home/bram/repos/abdomenmrus-cinemri-reader-study 
	/home/bram/repos/abdomenmrus-cinemri-registration  
	/home/bram/repos/abdomenmrus-cinemri-baselines  
	/home/bram/repos/iterative_unet
	/home/bram/repos/abdomenmrus-cinemri" 

# Initial sync
echo "Performing initial sync"
rsync -avz --exclude=".*" $paths $destination
echo "Initial sync done"

# Watch realtime changes
while true; do
inotifywait -r -e modify,create,delete,move --format "%f" $paths |
	while read filename; do
		echo "Detected changes in file: $filename"

		# Perform full sync
		rsync -avz --exclude=".*" $paths $destination
	done
done
