#!/bin/sh

# Script to automatically and realtime sync local changes to netcache

destination="/mnt/netcache/pelvis/projects/bram/repos"
paths="/home/bram/repos/abdomenmrus-cinemri-reader-study 
	/home/bram/repos/abdomenmrus-cinemri-registration  
	/home/bram/repos/abdomenmrus-cinemri-baselines  
	/home/bram/repos/iterative_unet
	/home/bram/repos/abdomenmrus-cinemri"

# Initial sync
echo "Performing initial sync"
rsync -avz --exclude=".*" --exclude="__*" $paths $destination
echo "Initial sync done"

# Watch realtime changes
while true; do
inotifywait -r -e modify,create,delete,move --format "%w" $paths |
	while read filename; do
		# Find watched path
		for path in $paths
		do
                    if [[ $filename == *$path* ]]; then
                        watched_path=$path
                    fi
                done
		echo "Detected changes in file: $watched_path"

		# Perform sync
		rsync -avz --exclude=".*" --exclude="__*" $watched_path $destination
	done
done
