#!/bin/sh

# Script to automatically and realtime sync local changes to netcache

destination_prefix="/mnt/netcache/pelvis/projects/bram/repos/"
source_prefix="/home/bram/repos/"
paths="abdomenmrus-cinemri-reader-study 
	abdomenmrus-cinemri-archive
	abdomenmrus-cinemri-patch-level
	abdomenmrus-cinemri-spatiotemporal
        universal-classifier-t9603
	flare22-brananas
	diag-nnunet
	nnunetv2
	nnUNet
	medvlp
	ugssl
	abdomenmrus-cinemri
	relearn
	stylegan3
	stylegan-xl
	PyTorch-StudioGAN
	pi-cai-chu
	abdomenmrus-cinemri-textual-inversion"

# Setup clsyncs
for path in $paths
do
    watch=$source_prefix$path
    dest=$destination_prefix$path

    clsync -Mrsyncdirect -W $watch -D $dest -R /home/bram/repos/dotfiles/scripts/sync_rules -w 0 -t 0 -b

    echo Now watching dir $watch
done
